packages:
  - zsh
  - python3
  - pip
  - vim
  - tmux
  - kubectl
  - fzf
ubuntu_packages:
  - silversearcher-ag
  - apt-transport-https
  - ca-certificates
  - fonts-powerline
fedora_packages:
  - openssl
  - bat
  - cmake
  - gcc-c++
  - make
  - golang
  - python3-devel
  - powerline-fonts
  - podman
  - buildah
  - the_silver_searcher
  - sqlite
  - wget
  - curl
  - sudo
  - ncurses
  - dnf-plugins-core
  - dnf-utils
  - passwd
  - findutils
  - procps-ng
  - iputils
  - iproute
  - vim
  - python-unversioned-command
pip_packages:
  - docker-compose
dotfiles:
  - .zshrc
  - .vimrc
  - .tmux.conf
  - .alacritty.yml
force_symlink: no
