packages:
  - zsh
  - python3
  - pip
  - vim
  - tmux
  - kubectl
ubuntu_packages:
  - silversearcher-ag
  - apt-transport-https
  - ca-certificates
fedora_packages:
  - podman
  - buildah
  - the_silver_searcher
dotfiles:
  - .zshrc
  - .vimrc
  - .tmux.conf