packages:
  - zsh
  - python3
  - pip
  - vim
  - tmux
  - kubectl
ubuntu_packages:
  - silversearcher-ag
  - apt-transport-https
  - ca-certificates
fedora_packages:
  - podman
  - buildah
  - the_silver_searcher
pip_packages:
  - docker-compose
dotfiles:
  - .zshrc
  - .vimrc
  - .tmux.conf
force_symlink: no
