packages:
  - zsh
  - python3
  - pip
  - vim
  - tmux
  - kubectl
  - fzf
ubuntu_packages:
  - silversearcher-ag
  - apt-transport-https
  - ca-certificates
  - fonts-powerline
fedora_packages:
  - code
  - alacritty
  - gnome-shell-extension-pop-shell
  - openssl
  - bat
  - cmake
  - gcc-c++
  - make
  - golang
  - python3-devel
  - powerline-fonts
  - podman
  - buildah
  - the_silver_searcher
  - xl2tpd
  - NetworkManager-l2tp
  - NetworkManager-l2tp-gnome
pip_packages:
  - docker-compose
dotfiles:
  - .zshrc
  - .vimrc
  - .tmux.conf
  - .alacritty.yml
force_symlink: no
