- hosts: localhost
  vars_files:
    - ./config.yml
    - ./secrets.yml
  tasks:
    - ansible.builtin.import_tasks: ./tasks/packages.yml
      tags: packages
    - ansible.builtin.import_tasks: ./tasks/dotfiles.yml
      tags: dotfiles
    - ansible.builtin.import_tasks: ./tasks/pip.yml
      tags: pip
    - ansible.builtin.import_tasks: ./tasks/kubectl-comp.yml
      tags: kubectl-comp
    - ansible.builtin.import_tasks: ./tasks/kubectx.yml
      tags: kubectx
    - ansible.builtin.import_tasks: ./tasks/minikube.yml
      tags: minikube
    - ansible.builtin.import_tasks: ./tasks/helm.yml
      tags: helm
