- name: clone dotfile repo
  ansible.builtin.git:
    repo: https://github.com/pyrsson/dotfiles.git
    dest: ~/github/dotfiles
    accept_hostkey: yes

- name: install ohmyzsh
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    accept_hostkey: yes
  when: lookup("fileglob", "~/.oh-my-zsh") == ""

- name: create links for dotfiles
  ansible.builtin.file:
    path: ~/{{ item }}
    state: link
    src: ~/github/dotfiles/{{ item }}
    force: "{{ force_symlink | default('no') }}"
  loop: "{{ dotfiles }}"

- name: set default shell to zsh
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    shell: /bin/zsh
  become: yes
